---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: system-monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
