# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: system-monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:jWfR2nQ=,iv:Q/9/TW9LVMg6Z5UFbO19JZDeSEAzMwulmc/NLisHPrQ=,tag:f4f+wni+kyfu5nToOBC5oQ==,type:str]
    admin-password: ENC[AES256_GCM,data:OiQ/lR/fa0bTLOeLyfotLjkW,iv:3kP/Cc+zMir5IkHuvqgrg2r4+nmrzVsXIypyWAeS15E=,tag:qarRmoAef6l8xpFrxFfrDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydk5SU2R4NjJEakN6ZTd6
            SjErU0h2NmR2dVV4VjdHd3lRbzV6QWxLT3c0CmRpZXRZeWY0MjFxcEdNMlNldWtK
            eG5zSFpZMkJDSEVGTWFBUndJVk1VZU0KLS0tIFRBYWYxYUVPYm42cGt6T3dLMmI2
            VzYvaTFyU1EzMU9GWjRkMCt3ejRjTUkKjFIU9u9NZ66nmD88dQDqiN+RsPT1qwL8
            T2NbqSdaG822D080/ObEiBUBYt2VaNZX8xMmn1HSRMMEYyTug14yDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T23:02:37Z"
    mac: ENC[AES256_GCM,data:md/HKzj9sFzyzGBTDIyX1UmDSQCYqwd2joF1JKa/AqGNEgKXqVlxC4nrpsFqmbZKMWLTeRboB/qviGOJQ0QQ97/KbrP0zO0mKnGRGpArDAeD9gAhDN2/H4S7KdM8cq9M7MRaX+4GBCyRi7V+Dw+M3S7p1yYdsmRipolfHmsXRQo=,iv:4dAKu14mLaQ+/AmybCRTI3llMRbThGlXrK1Tz5irUek=,tag:gEZABWOuVSwxKA1OVQbnUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
