kind: ConfigMap
apiVersion: v1
metadata:
    name: mailserver.env.config
    namespace: mailserver
    labels:
        app: mailserver
data:
    OVERRIDE_HOSTNAME: mail.greyrock.io
    ENABLE_FETCHMAIL: "0"
    FETCHMAIL_POLL: "120"
    ENABLE_CLAMAV: "0"
    ENABLE_FAIL2BAN: "0"
    ENABLE_SPAMASSASSIN: "1"
    SPAMASSASSIN_SPAM_TO_INBOX: "1"
    POSTFIX_MESSAGE_SIZE_LIMIT: "31457280"
    ENABLE_POSTGREY: "0"
    ONE_DIR: "1"
    DMS_DEBUG: "0"
    SSL_TYPE: manual
    SSL_CERT_PATH: /etc/ssl/mailserver/tls.crt
    SSL_KEY_PATH: /etc/ssl/mailserver/tls.key
    POSTFIX_INET_PROTOCOLS: ipv4
    RELAY_HOST: smtp.eu.mailgun.org
    RELAY_PORT: "587"
    RELAY_USER: postmaster@greyrock.io
    RELAY_PASSWORD: ENC[AES256_GCM,data:HxgWNDh8X924NnfgxA==,iv:PD/kXeMN+hi6R6ehC2zX79RCmWMhRuCWd1QCUEByfkM=,tag:YIZnPyhizT6PH+GVuNTkvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWXVrUFBvK0h2ZWN2ZjNP
            L2VSOEhqZ3lCczJxSWpoQmcxRUI5U3JVVTBRCnVJRitFSnErSmorc3dXY2hNK1ZP
            ejNpVzYxY0F0aG1PSHVScERLeGZFUWcKLS0tIENqWnN6TGVVR2ZqZCtJYWhZb2ZV
            Nlo2blZkd1dEOU12cVA1UnlYemF1TmcKwfrsrdCT2G7biIAPGCz6Np9Fo/dH5pXq
            jkyDSQJ+TVJiIlLdrDEMYyWPBV1wDOsn2+TgHd/DUcuB5cB6shfhoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-20T14:06:08Z"
    mac: ENC[AES256_GCM,data:Ir3LC6kapGaGlcHDilNOzDMOTDk+aeez1JAf6q3hoSchy8WlvruV/RaHsyh3/dDr93AqYW8ausbym3B/s2JUhtHQTIAO4qtcipW3HUBXEK0LF93jJCyk8b3sSBVLfruYacwko9K9aPe5BPS7SnTljkmikPYvGgnTL2gQzuI5j9E=,iv:2Ps9tEUl3+X0MkQ7BkSSa231AG6UQIHvBP+s5dFXiD8=,tag:Z7rljaRhmdfT/UMrwAgP0Q==,type:str]
    pgp: []
    encrypted_regex: PASSWORD
    version: 3.7.3
