---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage-data-v3
  namespace: mailserver
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
