---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.0.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: 7.0.4-debian-11-r4
    global:
      storageClass: longhorn
    auth:
      enabled: false
    master:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          coredns.io/hostname: "redis-master.${SECRET_DOMAIN}"
    replica:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          coredns.io/hostname: "redis-replica.${SECRET_DOMAIN}"
    useExternalDNS:
      enabled: true
      suffix: ${SECRET_DOMAIN}
      additionalAnnotations:
        ttl: 10
    metrics:
      enabled: true
      image:
        tag: 1.43.0-debian-11-r10
      serviceMonitor:
        enabled: true
