# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BJy8zeQhbrdx3cux,iv:McOmLhHq/48h9b+rQcMb615kdKDCZ9AL4zwuJNU25ak=,tag:9y6/j8fLLapJELip7g2o2w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CxeyunbZJcDU1UBq85qAcRyKFgiQlQ==,iv:+FxRuuZusyGfTDqAqGZxswAY09Pd2W1uneuFqNP74Xk=,tag:ANlTny9MaSE9/qqTCEXEhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTAyT0R0MHIvSW1CY2xn
            REN2QlJsRWFkOUFwbU1OeFJsOHJVWFhDLzNVCjNTV0dCaTM2Titsd0JSTzA2bXlj
            alhZcFZUWDllMmVrMWY3SkRrZ2VPYWMKLS0tIEI4Zzg2L3djS3NaYVJ2c082TU5m
            VkJjTGE0R1hpdHU0cTZET05sYklHUUUKuMsTs5K/E8FuFHxPSCzHw825o0bPXeFb
            wOTGu0xI94PgpE3Iu0ozKS1lUphNIdx9Fvkt4ADZ6aziLjtZEoTkew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-15T22:41:42Z"
    mac: ENC[AES256_GCM,data:GYsJJxXM6tlsCc3PCpqDQcWPXaQ2xoPmhD90jc93eiirGSORYIErkzNrn1Ol7V0tLfeBwmoN2T+91XX66Kwj5qSZ/8bDqJu9W5228+lv9b+8XyEnxPB8O0ofYQtPw65TXAvMaaX8HDXFcCBTMdRNCnORDODab5iJ9Xq0JEt7GdI=,iv:HBP1G8yd7TjYYbyCy0yR4s1W65R8Pmwo1jI2SffgxBk=,tag:TiBE5Q1v94LvYnZEDm+ZKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
