---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  METALLB_LB_RANGE: 172.16.30.100-172.16.30.149
  METALLB_K8S_GATEWAY_ADDR: 172.16.30.100
  METALLB_INGRESS_ADDR: 172.16.30.101
  SVC_EMQX_ADDR: 172.16.30.110
