# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jV2xrXf8DVVlrNM=,iv:r+ufhp5yz4C0g+dDd1SADpvtG1YcHqJm5PmJVAmZLlM=,tag:lZ5RHxy91hNCA2ZnxOHksQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CxeyunbZJcDU1UBq85qAcRyKFgiQlQ==,iv:+FxRuuZusyGfTDqAqGZxswAY09Pd2W1uneuFqNP74Xk=,tag:ANlTny9MaSE9/qqTCEXEhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTAyT0R0MHIvSW1CY2xn
            REN2QlJsRWFkOUFwbU1OeFJsOHJVWFhDLzNVCjNTV0dCaTM2Titsd0JSTzA2bXlj
            alhZcFZUWDllMmVrMWY3SkRrZ2VPYWMKLS0tIEI4Zzg2L3djS3NaYVJ2c082TU5m
            VkJjTGE0R1hpdHU0cTZET05sYklHUUUKuMsTs5K/E8FuFHxPSCzHw825o0bPXeFb
            wOTGu0xI94PgpE3Iu0ozKS1lUphNIdx9Fvkt4ADZ6aziLjtZEoTkew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-15T22:44:02Z"
    mac: ENC[AES256_GCM,data:BrN5qZJHDHnzAcDb2AFAoJSr7PIULETzVPXaF2Pv/Pw/n51gR+dO1KJB3y/YvcjAqO0a+vMsS8AhxULDnUe3QyphoVCjY/he657hfAO6D9qwrWeUNYPvdrng+tHLz3AZLPJpTxatCAK8FRGF7MofXUuMuJKQPSh3eIweGhtIHk0=,iv:VjaHnzojqcapD2SK9Pxv/vrPCZTF2/L/NH2ph2IZtpk=,tag:PfaYEcV5HD4LlUxPiQ+ygA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
