# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:15oPQnJID+9XOAg=,iv:fRxSg7gtjwy3WBB/ItJFiQu6A6bRqEVVJ46uKUZYmis=,tag:HBvppPY+7fdsNa2i9YRk1Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pJzDnzYgXhhgdsyzbraGZQ5nlZ77hg==,iv:8q6xy5dog9CtfNX00xw127nHP30uDtiQqduVvebfUMY=,tag:+iYMoIRU0l7rwJOI9dzpeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRjhCbWI3dmpIY1dyaWhv
            UmVDM1d2STJ0N3lDcVhITjFJVlc2SHRiZ1NRCi9lZFBoMkZmT1N2N25DSmFsWWFQ
            MXo5MnZBK1FwVjViSEx3SlliUlFJM0kKLS0tIE56NEFodmdSQWVjcldOdklqS3Fq
            aHlXcmFpZGFRVmhxS1JtMFFqY0RpOVUKiQKjvm+NNENOdyLSc4Vdclse9s97kv/x
            fUbDQhYc1Rv37v1BjXDn4RSFv4g2QoR76kIZVWat+PBZ9ad59DiXHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T17:29:06Z"
    mac: ENC[AES256_GCM,data:YNjMSviI28td0Vl3MRRkrgeMLtCmxjmMFIKKmzxr6UX15RV7VW89yWopZKa7LbK761PYF/UmYH2/K7Khp/R/A004mVAq+66oQKht+DiNSXPjouGHrpvA8XXsnPP7B3j36PtiCkl/xXypchRVku/gJRM4NiGuCOE1nc8dJ/y+8EQ=,iv:MbMSDWWSZ0HyQRk7GaMNheR08J0VM8pHO92txV/GfKo=,tag:THB+ejUzZg0+2d/4jho1hA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
