---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: openldap
spec:
  interval: 15m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: openldap
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: 1.5.0
    replicaCount: 3
    recreatePods: true
    global:
      ldapDomain: ${SECRET_DOMAIN}
      adminPassword: ${SECRET_OPENLDAP_ADMIN_PASSWORD}
      configPassword: ${SECRET_OPENLDAP_CONFIG_PASSWORD}
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        coredns.io/hostname: "ldap.${SECRET_DOMAIN}"
    env:
      LDAP_ORGANISATION: "Grey Rock"
      LDAP_RFC2307BIS_SCHEMA: "true"
    customTLS:
      enabled: true
      secret: "openldap-cert"  # The name of a kubernetes.io/tls type secret to use for TLS
    phpldapadmin:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "phpldapadmin.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: "phpldapadmin-tls"
      env:
        PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
    ltb-passwd:
      enabled: "true"
      ingress:
        enabled: true
        ingressClassName: "nginx"
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "ltb.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: "ltb-tls"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 8Gi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - openldap
              topologyKey: kubernetes.io/hostname
