kind: Secret
ansible_user: ENC[AES256_GCM,data:I0qZzA==,iv:NfPWl7ZnPDpaHjGdhKs1XIRXVyFR6UObSvhIbBbG93Y=,tag:mq+WmxjTXgxnsOuYYlkq5Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PcTV1eTERZD5,iv:q5QiP3HftrmThfx9UYiuxH9sMiVBlbAij75FzuigZF8=,tag:eHgYAnJeSIdms9+Qvdq9zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMUVpN1g2a2hMU2R6S052
            R0NtNC8xSkRQcFkvbXdqdE10NEk4ZUQxWTFrCi9FNnZhTzJvYXk5cjN3NjZ3eUkx
            Q2VNMExoU3NqWGZkSnVmT3EvcU5PRG8KLS0tIGxTVXcwakRGWWp3Y0RCQ2Ixejho
            TkRZTk9ENUxsQVIzY09NMnB1SHoyZ3cKSHf0Y/MN31+iz4xLpVBNomIyGFTt1G3c
            kFiBnCGegvVOamt///LrknU+YGrvzVZovxpO88TvMnE1w7XPaR1YFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T18:56:39Z"
    mac: ENC[AES256_GCM,data:EW2IaaIiG1FRzOqIN2y5yFotGTYoTzbHxeJdbF1rHrsmscNFyKTCzFBTgOGq1H/mlsvvmfiUNzgbM+AgF51KZRiU/9oOWyr+G7sMa5oF30TuNBvoqVicM0SbeHAVhFLUNH6QW98mgHzU7Ic4eJFZAHajYTLBAsik3r5ZkQ6qa7I=,iv:DxaUZRnTQRGPKK3oCUwx+pU01E+YYqaUNP/xtXAM5p4=,tag:Nk3JcOq/R5IOk95Ijcy8fQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
