kind: Secret
ansible_user: ENC[AES256_GCM,data:ClXT9Q==,iv:lM4hN4lTdkUFjUrIQgrQYD2HDPd5TNpRAs7NDaRg4f0=,tag:4P5qfNf0AOQZRjVvUsOeSw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0rODw1YBa9lP,iv:dV+NeJbJkfw2xHsBM4SJIJ6g7jio0AM1XIqgPOEfrKA=,tag:6Q5okQGv44RCZAb19zPrAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXRUQ210akdNSU9veG9C
            R05HOVRTc1l2NVlYbVRoRFpZdkd0SXUxV1VnCjBWSVVjd0t0bTEyMDZEeHFOOENM
            K0d0bGVRVHpiZmpZWklFMHg3Nit0d2cKLS0tIGZoV2lyZjBVZmdJTTMrYzlpemlH
            U1luOE9sMXczaTF6M1FCdGE5TnVEWDQK4Ob2j5kCTAChLwfeKdMW60Ij1TH+YJ5d
            VteEaLeejgj6ICF/N3/Y0kY37LOlw/GBU69uU51EMihEe54hyCTZ5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T18:56:40Z"
    mac: ENC[AES256_GCM,data:tORwhaspB0mfoc9AP8zsru7OVjuOtceufA/q4cJ4Vg+lJ3wJpBdEBYcyspDVkoPxFWgtHAwSPS0Y9oeV2b3POpaP7RKGFb6ECP57iaruy4jLXHDldQl1LM9XvfbCjO9GmuOCf7dnyztV/6QayA7y3Mh1zdehD9Vr91A4ClfjLt8=,iv:o1y7j1wTDE8N1NvUFB8l/e6E+8qFWsOGC6xpQXZHcXU=,tag:2EiOUQ2LbUYNB4OyYW+uhw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
