kind: Secret
ansible_user: ENC[AES256_GCM,data:m5YJ4A==,iv:m+M1Lx0CsZSZG8oqWbSrfKL0zHkuyBCM8OrOssxHYLk=,tag:zaT71o/8EE7aiQxqeLWNgQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2hjhCddat/nX,iv:L/Y9GYXODDlx0qguNjBOb9joRQIuPDm+v2Md9mUXqys=,tag:49yMf/qL1mftCK4NktOhiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc04wN0FCL2dSL0FjVk5Y
            bDcwUWgwODBzVW16UUhodHdxd0VVdk1ubUhrCnFFMGRwSURCY2orejdlQWtDWXdW
            VHVTcVZTbG8wekJ2RWJRTTkyV1dhVEkKLS0tIHUxQmdaZmYyK3p3cDQ3ang5WW14
            ZmZKMFk5bUF2cE16aTFBcFVSSWJZT0UKYhw3dBanx/KfwGrPx7W2SBcussH3nhve
            QsN0ZTvIMsVQtqLAU3dgYzEI/meloQ2qZFdq7PBICpZXSTpDsinAVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T18:56:40Z"
    mac: ENC[AES256_GCM,data:lgecXh0NpX0eRx8MmzbpqRUYfNnw4l3gZt1tw1+pjfUJcAGUgt3fRx76NlwXnRNBwbKiBGmdTQbqTFIUwcyLVNrfQdfdnP6hQYiER3LxL4xUphLO3Fbpqmsv4IALcD6IWc5UToxaWYmTO5baTB9VaRjGCJTSFgLAzxoY+I5kt6c=,iv:doU+lS+jiq0PIBi7jsYASNkSlbCGHvxKqfXZMhJW8pU=,tag:nVfxEuVIu7dgGGyH3fPTnw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
