---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pdns
  namespace: mariadb
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb-galera
      version: 7.3.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: 10.6.8-debian-11-r0
    global:
      storageClass: longhorn
    service:
      type: LoadBalancer
      annotations:
        coredns.io/hostname: "mariadb-pdns.${SECRET_DOMAIN}"
    rootUser:
      password: ${SECRET_MARIADB_ROOT_PASSWORD}
      forcePassword: true
    db:
      user: pdns
      password: ${SECRET_MARIADB_PDNS_USER_PASSWORD}
      name: pdns
      forcePassword: true
    galera:
      mariabackup:
        password: ${SECRET_MARIADB_PDNS_GALERA_BACKUP_PASSWORD}
      bootstrap:
        bootstrapFromNode: true
        forceSafeToBootstrap: true
    metrics:
      enabled: true
    primary:
      podManagementPolicy: Parallel
