---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pdns
  namespace: mariadb
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: 10.6.8-debian-11-r0
    global:
      storageClass: longhorn
    primary:
      service:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: "mariadb-pdns.${SECRET_DOMAIN}"
    auth:
      rootPassword: ${SECRET_MARIADB_ROOT_PASSWORD}
      database: pdns
      username: pdns
      password: ${SECRET_MARIADB_PDNS_USER_PASSWORD}
    metrics:
      enabled: true
