kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-config
    namespace: home
stringData:
    admin_password: ENC[AES256_GCM,data:7RF3aSkNZIV1KmtPxiji2R+0,iv:+1yhqKl8fsgrk7QArYJtEBfkMiSOhatcJqwbd956/70=,tag:QjNQGCmtV5y4lg3VZ+hUUg==,type:str]
    user_1_username: ENC[AES256_GCM,data:WlB7S8FgeTNS,iv:a9QDs4MiI1DDUWHsX0OHmfcsYunGyoJFC+b/puaSWAA=,tag:BO779jWpIUTWU/4RvbwKUg==,type:str]
    user_1_password: ENC[AES256_GCM,data:6G/+1hGzhmNowDyJEXtkJcazRCvSHjkRl5UL/QYj,iv:wXjaF9fqA9ASBJrMZyO6B4rJ+wEX5aMIvgJFc4znx7A=,tag:h9eV0rvkZzkC4+K6Vf5D+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12e0fdd0qrge7ccnhgzdk2yp3w5kxg45cspcy4sms0n3ywd2055wsjy06kj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2lHNzBHN2EwcmkyTVlW
            TFFramtpdm1LSGZDTVlrNlhXajZ0Mi9oQ3dZCjFVMW9TK2lTbDdLSkV1VHZ0MHIr
            dEJ6Q1ovcWQ3dVhoTmk2c1RNTll4dkEKLS0tIE51d3pxbUlEV3ZndnN3TXROTlJr
            TkVsUnRVNW1hdWMxazFxUXRPaEI4dDAKXiOaLFuMgG/yF1H5a91jhO4qvWOD9daF
            7r5rR3Vtl7vi5/CokK7UgOgczeMgs54/MfTTlLg2KrY5UitHOSu7wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T15:12:27Z"
    mac: ENC[AES256_GCM,data:3X35BCE9ojRSV8ODW6KB8LflsAZUXsV4T9dQxhbG4JSQWiV805hoD5lyZTuituoXAe2j7vuDFo0LAvPBtnWqYWookeojI7rnCJNxwPxOoO7gzIaXn08ypoTs74fqy0iRIBu8jUNacBw6k9JrWjzSzW5ZPXjInQjxcAPqlHSwt88=,iv:R+aO+MNetIgXB/wwm8X5FwyIll+XoV82YgLDKrXbz7s=,tag:euv7c5ZYtIKONDT5qsA9Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
